export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCHING_DATA_SUCCESS = 'FETCHING_DATA_SUCCESS';
export const POST_READ = 'POST_READ';
export const ADD_TO_FAVORITE = 'ADD_TO_FAVORITE';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const REMOVE_ALL_POSTS = 'REMOVE_ALL_POSTS';
